drop table trained_in;
drop table Undergoes;
drop table stay;
drop table on_call;
drop table room;
drop table block;
drop table prescribe;
drop table medication;
drop table appointment;
drop table nurse;
drop table patient;
drop table procedure;
drop table affiliated_with;
drop table department;
drop table physician;

delete from trained_in;
delete from Undergoes;
delete from stay;
delete from on_call;
delete from room;
delete from block;
delete from prescribe;
delete from medication;
delete from appointment;
delete from nurse;
delete from patient;
delete from procedure;
delete from affiliated_with;
delete from department;
delete from physician;

select * from trained_in;
select * from Undergoes;
select * from stay;
select * from on_call;
select * from room;
select * from block;
select * from prescribe;
select * from medication;
select * from appointment;
select * from nurse;
select * from patient;
select * from procedure;
select * from affiliated_with;
select * from department;
select * from physician;